import type { Profile } from '@/types'

export const DEMO_PROFILES: Profile[] = [
  {
    id: 'f2d41b4e-5fd0-4f03-9a9f-66d8f8893c27',
    username: 'jibraan-mukhtar',
    full_name: 'Jibraan Mukhtar',
    role: 'operator',
    status: 'approved',
    headline: 'Data Scientist at You.com building retrieval and ranking systems for AI search.',
    bio: 'Applied ML engineer focused on LLM evaluation, recommender systems, and production experimentation. Previously worked on fraud models and large-scale feature pipelines.',
    company: 'You.com',
    company_url: 'https://you.com',
    company_stage: 'growth',
    metrics: 'Improved answer relevance +11% and reduced hallucination flags by 23% across key search flows.',
    past_work: 'Ex-ML at fintech (risk scoring). Built offline/online model monitoring and experimentation frameworks.',
    open_to: ['advising', 'hiring'],
    linkedin_url: 'https://linkedin.com/in/jibraan-mukhtar',
    twitter_url: 'https://x.com/jibraan',
    website_url: 'https://you.com',
    location: 'Bengaluru, India',
    invite_slots: 3,
    created_at: '2026-04-10T12:00:00.000Z',
    updated_at: '2026-04-10T12:00:00.000Z',
  },
  {
    id: 'c2e6306e-5195-4908-8be8-5ca755db8a2e',
    username: 'ananya-rai',
    full_name: 'Ananya Rai',
    role: 'founder',
    status: 'approved',
    headline: 'Founder at LedgerLoop, automating finance ops for mid-market companies.',
    bio: 'Second-time founder. Building tools that remove repetitive workflows from CFO teams and finance operators.',
    company: 'LedgerLoop',
    company_stage: 'seed',
    metrics: '$42k MRR, 110 active companies, 2.8% monthly logo churn.',
    past_work: 'Ex-Stripe partnerships. Built GTM from 0 to first 50 paying customers.',
    open_to: ['funding', 'hiring'],
    linkedin_url: 'https://linkedin.com/in/ananya-rai',
    twitter_url: 'https://x.com/ananyabuilds',
    location: 'Mumbai, India',
    invite_slots: 3,
    created_at: '2026-04-10T11:30:00.000Z',
    updated_at: '2026-04-10T11:30:00.000Z',
  },
  {
    id: 'cfeb9931-8dc8-4d44-9ad8-7fec6b31ea94',
    username: 'rahul-safdar',
    full_name: 'Rahul Safdar',
    role: 'vc',
    status: 'approved',
    headline: 'Partner at Northarc Ventures investing in applied AI and vertical SaaS.',
    bio: 'Backed early teams across AI infrastructure, devtools, and workflow automation. Strong focus on founder velocity.',
    fund_name: 'Northarc Ventures',
    check_size: '$500K–$2M',
    sectors: ['AI', 'SaaS', 'Developer tools'],
    metrics: '18 portfolio companies, 4 Series A follow-ons in the last 12 months.',
    past_work: 'Former operator at a growth-stage SaaS company before moving to investing.',
    open_to: ['investing', 'advising'],
    linkedin_url: 'https://linkedin.com/in/rahul-safdar',
    location: 'Dubai, UAE',
    invite_slots: 3,
    created_at: '2026-04-10T11:00:00.000Z',
    updated_at: '2026-04-10T11:00:00.000Z',
  },
  {
    id: 'b9c7ae0d-e4f8-4d66-8851-80ce074947e9',
    username: 'sana-khalid',
    full_name: 'Sana Khalid',
    role: 'operator',
    status: 'approved',
    headline: 'Product leader scaling AI onboarding and activation flows.',
    bio: 'I help teams improve activation, retention, and monetization through product experimentation and customer research.',
    company: 'NovaStack',
    company_stage: 'series-a',
    metrics: 'Lifted activation from 31% to 49% over 2 quarters.',
    past_work: 'Ex-Notion growth team, then first PM at two seed-stage startups.',
    open_to: ['hiring', 'advising'],
    linkedin_url: 'https://linkedin.com/in/sana-khalid',
    location: 'Bengaluru, India',
    invite_slots: 3,
    created_at: '2026-04-10T10:30:00.000Z',
    updated_at: '2026-04-10T10:30:00.000Z',
  },
  {
    id: '4132f7f9-eb46-4970-a33c-aa7e4f8f1c1d',
    username: 'ziyaan-mir',
    full_name: 'Ziyaan Mir',
    role: 'angel',
    status: 'approved',
    headline: 'Angel investor focused on data infrastructure and B2B AI products.',
    bio: 'Operator-turned-angel backing technical founders at pre-seed and seed stages.',
    metrics: '27 angel checks, 8 follow-on rounds, 3 portfolio exits.',
    past_work: 'Built and exited analytics startup; former engineering lead at cloud infra company.',
    open_to: ['investing', 'cofounders'],
    linkedin_url: 'https://linkedin.com/in/ziyaan-mir',
    location: 'Singapore',
    invite_slots: 3,
    created_at: '2026-04-10T10:00:00.000Z',
    updated_at: '2026-04-10T10:00:00.000Z',
  },
]

export const DEMO_POSTS_BY_USERNAME: Record<string, { id: string; content: string; created_at: string }[]> = {
  'jibraan-mukhtar': [
    {
      id: 'demo-post-j-1',
      content:
        'Just wrapped an internal study on LLM answer quality in long-tail queries. Biggest lesson: better context compression beats larger prompts in most practical cases.',
      created_at: '2026-04-08T12:00:00.000Z',
    },
    {
      id: 'demo-post-j-2',
      content:
        'Open to advising early AI startups on retrieval quality, eval design, and moving from notebook experiments to production-safe pipelines.',
      created_at: '2026-04-05T12:00:00.000Z',
    },
  ],
  'ananya-rai': [
    {
      id: 'demo-post-a-1',
      content:
        'Looking for a staff-level backend engineer who has shipped billing and ledger systems at scale. Prefer async-first and high ownership.',
      created_at: '2026-04-09T09:30:00.000Z',
    },
    {
      id: 'demo-post-a-2',
      content:
        'Closed 7 new pilots this month from CFO referral loops. Sharing our outbound script and onboarding checklist if useful to other founders.',
      created_at: '2026-04-06T11:00:00.000Z',
    },
  ],
  'rahul-safdar': [
    {
      id: 'demo-post-r-1',
      content:
        'Hosting founder office hours next Thursday. Looking to meet teams building workflow AI with clear distribution angles.',
      created_at: '2026-04-07T16:00:00.000Z',
    },
  ],
}
